### ISSUE TITLE
Demo link fails

### ISSUE THREAD

**Issue by TimvdLippe** [rnicholus/ajax-form#82] opened 2016-05-08 22:05 UTC
Opening http://ajax-form.raynicholus.com/ will results in an empty page with a failed DNS lookup.

**Comment by rnicholus** [comment] 2016-05-08 22:25
Thanks so much for bringing this to my attention, it must have happened when I switched domain registrars. 

The issue is now fixed, and you should _probably_ see the demo + docs at http://ajax-form-raynicholus.com now or very shortly from now.

**Closed by rnicholus** 2016-05-08 22:25 UTC

**Comment by TimvdLippe** [comment] 2016-05-08 22:26
Yes can confirm it is live again. Thanks for the quick fix!

**Comment by TimvdLippe** [comment] 2016-05-08 22:27
One minor issue, the polyfill seems to 404: 
![image](https://cloud.githubusercontent.com/assets/5948271/15100755/df6d6222-157c-11e6-9177-915faac7efc3.png)

**Comment by rnicholus** [comment] 2016-05-08 22:28
can you open up a new issue for that please?

**Comment by rnicholus** [comment] 2016-05-08 22:40
Probably didn't notice the missing polyfill myself as I'm not really using WC anymore (at the moment) and I usually only open this demo is Chrome (which doesn't need any polyfill). Not sure when this broke, but probably relatively recently. Fixed in #83.
