### ISSUE TITLE
paper-dropdown-menu still not submitting the values

### ISSUE THREAD

**Issue by ahmedali5530** [rnicholus/ajax-form#74] opened 2015-11-06 16:55 UTC
Hi @rnicholus ,
I have started using this library since today with Polymer Forms, it is working well with other elements but it is not submitting the value of `paper-dropdown-menu`. I m using `name` attribute in `paper-dropdown-menu` but not working.
Here is the code i m using in,
```
<paper-dropdown-menu class="block" name="pastry" label="Your favourite pastry">
	<paper-menu class="dropdown-content block">
	      <paper-item class="">Croissant</paper-item>
              <paper-item>Donut</paper-item>
	      <paper-item>Financier</paper-item>
	      <paper-item>Madeleine</paper-item>
	</paper-menu>
</paper-dropdown-menu>
```
Any suggestions will be appreciated.

**Comment by rnicholus** [comment] 2015-11-06 17:42
Please see #73. If the changes I committed in the associated branch fixes the issue for you, please comment in that case and I will consider resurrecting it.

**Closed by rnicholus** 2015-11-06 17:42 UTC

**Comment by ahmedali5530** [comment] 2015-11-07 13:16
Thanks @rnicholus for a quick reply, but this did not helped me :disappointed:

**Comment by rnicholus** [comment] 2015-11-07 17:34
How did you test out the code referenced in that case?

**Comment by ahmedali5530** [comment] 2015-11-09 05:17
I copied the code from [this](https://github.com/rnicholus/ajax-form/blob/hotfix/2.1.1/ajax-form.js) branch and try to submit the form.

**Comment by rnicholus** [comment] 2015-11-09 05:51
Please take a few moments to determine exactly what the issue is. Once that is established, I will be more than happy to make the proper adjustments to my code, assuming it is at fault.
