### ISSUE TITLE
<select> element value submitted as array

### ISSUE THREAD

**Issue by julesbou** [rnicholus/ajax-form#84] opened 2016-05-24 13:12 UTC
Hello there,

See https://github.com/rnicholus/ajax-form/blob/master/ajax-form.js#L255-264

I'm surprised that the submitted value of a `<select>` element is an array, in fact I understand it could be the case if it was a multiple select, but in my case it's not.

**Comment by rnicholus** [comment] 2016-05-24 13:18
Is there a specific issue you are seeing with the request sent to your server endpoint?

**Comment by julesbou** [comment] 2016-05-24 13:21
yes,

JSON sent to my server: `{"selectField":["false"] }`
I was expecting: `{"selectField":"false"}`


html I'm using:

```
<select name="selectField" require>
  <option></option>
  <option value="true>Yes</option>
  <option value="false">False</option>
</select>
```

**Comment by rnicholus** [comment] 2016-05-24 13:38
Looking at my tests, this is the expected behavior. Also, there is no standard from which to compare this behavior to since HTML forms are not capable of encoding fields as JSON. To me, it makes sense to represent this value as an array at all times, for consistency. This way, your server code doesn't need to be aware of whether the underlying field is multi-select or not. Also, what if the field _is_ multi select, but only one value is selected? Should the value be an array, or not? To me, it makes more sense for the value to always be an array.

**Comment by julesbou** [comment] 2016-05-24 13:53
I think you should rely more on the way browsers are actually doing.

When submitting this form:

```
<form action="/server" method="post">

<select name="selectField" required>
  <option></option>
  <option value="true" selected>Yes</option>
  <option value="false">False</option>
</select>

</form>
```

`/server` endpoint will receive (in pseudo JSON): `{"selectField":"true"}`.

Why would your library behave differently and decides that the value should be an array?


> This way, your server code doesn't need to be aware of whether the underlying field is multi-select or not.

I totally agree, the server should never be aware of that.

>  Also, what if the field is multi select, but only one value is selected? Should the value be an array, or not? 

Simple, if multiselect, the value will *always* be an array. If simple select, the value will *always* be a string.

**Comment by rnicholus** [comment] 2016-05-24 13:55
>I think you should rely more on the way browsers are actually doing.

Again, there is no standard to compare this behavior to. Browser are not able to serialize a form as JSON natively.

**Comment by julesbou** [comment] 2016-05-24 13:58
Right, but we should follow data structure sent by browsers as close as possible, else people using your library will have to update their backend because we don't follow the way browsers are actually doing.

**Comment by rnicholus** [comment] 2016-05-24 14:03
>Right, but we should follow data structure sent by browsers as close as possible, else people using your library will have to update their backend because we don't follow the way browsers are actually doing.

It seems like we are going in circles here. There is no precedent for this behavior, so there is no standardize expectations for receiving a JSON representation of a form. No browser is able to convert a form into JSON, so there isn't an expectation of a specific behavior.

I'm going to close this case as I'm not seeing a compelling reason to introduce a breaking change here.

**Closed by rnicholus** 2016-05-24 14:03 UTC

**Comment by julesbou** [comment] 2016-05-24 14:05
@rnicholus do you have experience working with a language use in a backend, like php, ruby, python? I just want to show you a quick example if you don't mind. Then you can close the discussion =)

**Comment by rnicholus** [comment] 2016-05-24 14:07
I work with Java often, as well as Node.js, and have written PHP backends for various libraries I maintain. Regardless of the backend, JSON is JSON is JSON. In this case, simply expect that the value will be an array. If you are only ever expecting one value in your `<select>` elements, then your focus can be on the first array element.

**Comment by julesbou** [comment] 2016-05-24 14:41
@rnicholus I understand that you want to keep backward compatibility in your library.

Here's a simple php example:

```html
<form method="post">
  <select name="single">
    <option value="1">One</option>
    <option value="2">Two</option>
    <option value="3">Three</option>
  </select>
  <select name="multiple[]" multiple>
    <option value="1">One</option>
    <option value="2">Two</option>
    <option value="3">Three</option>
  </select>

  <input type="submit" value="Submit">
</form>

<pre>
<?php

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  echo "--- raw data\n\n";
  print_r($_POST);

  echo "\n\n";

  echo "--- json data\n\n";
  print_r(json_encode($_POST));
}
?>
</pre>
```

You can easily run it with `php -S localhost:8000`.

Here's a screenshot of the result:

<img width="455" alt="capture d ecran 2016-05-24 a 16 39 28" src="https://cloud.githubusercontent.com/assets/328303/15508007/1d1f4d58-21ce-11e6-940a-096a62bc7cd5.png">


We could get this example running with python, ruby or any other language, the result will always be the same, across every browser and every language, why? Because browsers have a standardized way of sending form's data through HTTP.

You can't say JSON is JSON is JSON and let me do the way I want.
JSON is DATA is DATA, and the data format you're using is not the standardized one.

Kind regards,
Jules

**Comment by rnicholus** [comment] 2016-05-24 14:47
The problem with your example above is that the data is not sent as JSON. It is sent form-urlencoded (the default enctype for HTML forms). We are talking about a very specific format, JSON, that is not currently sent by browsers when a form is submitted. As long as ajax-form is sending valid JSON (and it is as far as I can tell) then your server should have no problem parsing the data using standard JSON response parsing tools.

**Comment by julesbou** [comment] 2016-05-24 14:58
I understand that you want to keep the actual behavior, which is fine, thanks for your time.
