### ISSUE TITLE
Ajax-form ignores formaction attribute

### ISSUE THREAD

**Issue by eximius313** [rnicholus/ajax-form#79] opened 2016-01-02 21:58 UTC
As w3c [documentation](http://www.w3schools.com/tags/att_button_formaction.asp) states one can use ```formaction``` attribute of a button in order to change form's ```action``` property:
```
<button type="submit" formaction="/action_one">First action</button>
<button type="submit" formaction="/action_two">Second action</button>
```
unfortunately ```ajax-form``` ignores this property

**Comment by rnicholus** [comment] 2016-01-03 00:13
Looks like I also need to account for formenctype and formmethod button
attributes here. I'll look into adding this support in the near future.

**Comment by eximius313** [comment] 2016-01-03 00:25
thanks!

**Comment by rnicholus** [comment] 2016-01-08 14:27
Working on this now. Once completed, it will be released as 2.2.0. I'd like for you to verify the updated code before release though @eximius313.

**Comment by eximius313** [comment] 2016-01-08 14:44
sure

**Comment by rnicholus** [comment] 2016-01-08 14:55
There are a few situations to cover here:

- [ ] `<button>` with one of these attributes is selected - form attributes are overridden on submit
- [ ] `<input type="submit">` with one of these attributes is selected - form attributes are overridden on submit
- [ ] User hits enter on the last input field in the form. The nearest `<button>` or `<input type="submit">` is checked for one of the three attributes listed in this case. If any exist, they are used instead of the matching form attribute.

**Comment by rnicholus** [comment] 2016-01-09 11:46
This is a bit more complicated than I imagined. I thought I had this working, but after looking closer, I'm convinced that there is no way to reproduce this native browser behavior correctly in all cases. This will have to be a limitation of the library.

**Closed by rnicholus** 2016-01-09 11:46 UTC
Labels: enhancement

**Comment by rnicholus** [comment] 2016-01-09 11:48
...I _am_ open to suggestions regarding other ways, via the API, that ajax-form can support on-the-fly changes to action, enctype, and method though.

**Comment by eximius313** [comment] 2016-01-11 00:39
But what was the problem?
