### ISSUE TITLE
Ajax-form ignores regular checkbox group

### ISSUE THREAD

**Issue by eximius313** [rnicholus/ajax-form#60] opened 2015-04-22 18:42 UTC
When I have a form with following input group (generated by "@inputCheckboxGroup" in Play Framework"):
```javascript
<span class="buttonset" id="test2">  
        <input type="checkbox" id="test2_PRESIDENT" name="test2[]" value="PRESIDENT"  />
        <label for="test2_PRESIDENT">President</label>
      
        <input type="checkbox" id="test2_CEO" name="test2[]" value="CEO" checked="checked" />
        <label for="test2_CEO">Ceo</label>
      
        <input type="checkbox" id="test2_SPECIALIST" name="test2[]" value="SPECIALIST" checked="checked" />
        <label for="test2_SPECIALIST">Specialist</label>
  </span>
```
The regular form sends the FormData (in request headers) like this:
```javascript
test2[]:CEO
test2[]:SPECIALIST
```
Unfortunately ajax-form sends it like this
```javascript
test2[]:VALUE_OF_LAST_CHECKBOX_ONLY
```
Why is that happening?

**Comment by rnicholus** [comment] 2015-04-22 18:49
Duplicate of #48 & #57.

**Closed by rnicholus** 2015-04-22 18:49 UTC
